- name: Install OpenVPN
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables
    - openvpn
    - easy-rsa

- include_vars:
    file: netmask.yml

- include_tasks: system.yml
- include_tasks: iptables.yml
- include_tasks: pki.yml
- include_tasks: openvpn.yml
- include_tasks: client.yml