- name: Copy easy-rsa
  shell: cp -a /usr/share/easy-rsa /etc/openvpn
  args:
    creates: /etc/openvpn/easy-rsa

- name: Copy easy-rsa vars
  template:
    src: easy-rsa-vars.j2
    dest: /etc/openvpn/easy-rsa/vars
    backup: yes
    mode: 0644

# Fixes a bug in Debian Stretch. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851059
- name: Link openssl.cnf
  file:
    src: /etc/openvpn/easy-rsa/openssl-1.0.0.cnf
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    state: link
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version|int == 9

# Fails with default shell, so bash is used instead
- name: Initialize PKI
  shell: |
    source ./vars
    ./clean-all
  args:
    chdir: /etc/openvpn/easy-rsa/
    executable: /bin/bash
    creates: /etc/openvpn/easy-rsa/keys

- name: Build CA
  shell: |
    source ./vars
    ./build-ca --batch
  args:
    chdir: /etc/openvpn/easy-rsa/
    executable: /bin/bash
    creates: /etc/openvpn/easy-rsa/keys/ca.crt

- name: Build DH
  shell: |
    source ./vars
    ./build-dh --batch
  args:
    chdir: /etc/openvpn/easy-rsa/
    executable: /bin/bash
    creates: /etc/openvpn/easy-rsa/keys/dh{{ _openvpn_key_size }}.pem

- name: Generate TLS key
  shell: |
    openvpn --genkey --secret keys/ta.key
  args:
    chdir: /etc/openvpn/easy-rsa/
    creates: /etc/openvpn/easy-rsa/keys/ta.key

- name: Build server key
  shell: |
    source ./vars
    ./build-key-server --batch {{ _openvpn_host }}
  args:
    chdir: /etc/openvpn/easy-rsa/
    executable: /bin/bash
    creates: /etc/openvpn/easy-rsa/keys/{{ _openvpn_host }}.crt
