- name: reload sysctl
  shell: sysctl --system

- name: reload iptables
  shell: /etc/network/if-up.d/iptables-restore

- name: restart openvpn
  service:
    name: openvpn@server
    state: restarted